language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"

before_install:
- pwd
- ls -alh
- touch .npmignore

jobs:
  include:
    - stage: build
      script:
        - npm run build
    - stage: test
      script:
        - npm test

